### PR TITLE
feat(influxdb): add path and protocol to config input

### LINKED ISSUE #205: Bug: support directory path in influxdb uri and HTTPS requests to influxdb
The current implementation does not allow setting https (when port 443 is used for example to access the system).

It is also not possible to add a subdirectory path to use an influxdb hosted behind a reverse proxy in a directory location.

For example I would like to connect to my influxdb at `https://example.com:443/victron-influxdb/`.

Currently, the connection attempt to port 443 is still done using http, resulting in a 400 error due to the wrong protocol.

### PR DESCRIPTION
**Pull request by maurerle**
Draft PR to add protocol and path to influxdb client

closes #205

### CODE REVIEW

**Comment by maurerle** [comment]
tested and works well :)

**Comment by mman** [comment]
This looks pretty clean and nice @maurerle, let me please just re-test it in my environments and I think it will be ready to merge...

**Comment by mman** [comment]
@maurerle I have (with your kind permission) adjusted couple things to make it better fit the rest of the code.

The InfluxDB settings layout is now responsive single line to consume less space. The `http|https` is now specified for app config where I think it belongs, and not just for the InflxuDBBackend... the rest is just tweaks and housekeeping and addressing TS errors...

Could you please test whether it works as expected before we merge it?

**Comment by maurerle** [comment]
works well, LGTM :)

**Pull request merged**
